events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 10M;

    # Diz para o NGINX confiar no cabeçalho X-Forwarded-For vindo do próprio Docker
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  192.168.0.0/16;
    set_real_ip_from  10.0.0.0/8;
    set_real_ip_from  0.0.0.0/0; # Força a aceitação do cabeçalho em ambiente de teste local
    
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;

    upstream front_service    { server front:8081; }
    upstream document_service { server document-service:8083; }
    upstream face_service     { server face-recognition:5000; }

    server {
        listen 8082;

        location /health {
            access_log off;
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }

        location / {
            proxy_pass         http://front_service;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }

        location /docs/ {
            proxy_pass         http://document_service/docs/;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }

        location /face/ {
            proxy_pass         http://face_service/;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_read_timeout 30s;
            proxy_send_timeout 30s;
        }
    }
}
