FROM python:3.10-slim

# Dependências atualizadas do sistema para OpenCV (Debian Moderno)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--workers=1", "--timeout=60", "--bind=0.0.0.0:5000", "app:app"]
